### ISSUE TITLE
Why is replication factor capped at 6?

### ISSUE THREAD

**Issue by anjor** [application-research/delta#120]
https://github.com/application-research/delta/blob/main/api/deal.go#L2237

**Comment by alvin-reyes** [comment]
This was based on EstuaryV1 configuration but there's no reason to follow this cap so I'll be removing this cap on the next release.

**Comment by anjor** [comment]
Can you explain why it makes sense?

**Comment by anjor** [comment]
Why is recreating/retrying deals expensive?

**Comment by alvin-reyes** [comment]
Every replication is a logged as an entry on delta so if we allow say 1000000 replications - it'll try 1000000 replications all at once (trickled to number of cores) - if its set to auto_retry then any failures will be retried. Each retry will be logged on a table called content_deals - so you can imagine that if you have 1M replications, if 30% of them failed, there's going to be another 400000 entries for retries. 

Capping it seems the right approach and if someone has a special case of replicating it 1000000 times, then they can build delta with their own limit.

**Comment by alvin-reyes** [comment]
What we can do is make this replication factor configurable so anyone can set it on the environment variable and use that number on the validation.

**Comment by anjor** [comment]
Yeah I have seen clients wanting up to 10x replication. 

Perhaps up the limit from 6 to 10 and then make it configurable.

**Comment by alvin-reyes** [comment]
Thanks! 

The replication factor is configurable by setting `MAX_REPLICATION_FACTOR` on the .env variable.
