### ISSUE TITLE
Delta Dataset Manager: Getting Started

### ISSUE THREAD

**Issue by jimmylee** [application-research/delta#98]
# Delta Dataset Manager: Getting Started

Interested in setting up Delta Dataset Manager as a Data Preparer/Onboarder? Follow this guide!

This guide will walkthrough the set-up of Delta and DDM in a standalone deployment, then show you how to add a dataset, content, wallets, SPs, and finally create replications.

### Prerequisites
- The following should work on macOS, as well as any Linux distro 
- Prerequisites: Go v1.19+, Rust v1.65+ OR Docker/Docker Compose
- Minimal CPU/RAM/Disk - this is a very lightweight application and should be able to run on a small VM

### Install (Baremetal)
Follow the instructions in the quick-start section in [Delta Standalone Repository](https://github.com/application-research/delta-standalone#quick-start)

Set-up can be done in a few minutes with just a single command. 

Follow the instructions as indicated and save your Delta API key.

### Install (Docker Compose)
Coming soon!

### 0. Verify Installation
Verify that the set-up was successful by running the following command:

```bash
ps -aux | grep delta
```

You should see **three** Delta processes running: `delta`, `delta-dm` and `node` (for NextJS/React Frontend) 

```shell
root     1980744  0.0  0.0   6244  2408 pts/11   S+   22:57   0:00 grep delta
root     3860935  9.9  0.1 11331296 2095992 ?    Sl   Apr07 605:54 ./delta/delta daemon --mode=standalone
root     3861546  0.0  0.0 2869124 30644 ?       Sl   Apr07   0:39 ./delta-dm/delta-dm daemon
root     3861647  0.0  0.0 11156624 56728 ?      Sl   Apr07   0:06 node ./delta-standalone/delta-nextjs-client/node_modules/.bin/next
```

Verify that you can access to the DDM UI by visiting `http://localhost:3000` on the server where you installed Delta.

Paste in the Delta API key, and specify the URL where Delta-DM is running (same server, default port is 1314).

Source `delta.env` to set the environment variables if you'd like to use the CLI.

### 1. Create a Dataset

**By UI**

Create a dataset by clicking on the `+ New Dataset` button on the top left corner of the DDM UI.
Fill in the details of the dataset and click `Create Dataset`.

<img src="../assets/ddm-add-dataset.png" width=500/>

**By CLI**
```bash
./delta-dm dataset add --name radiant-earth-ml --replication-quota 6 --duration 540 --unsealed true --indexed true
```

### 2. Add wallet 
**By CLI**
Wallets must be added via the DDM CLI for security reasons.

```bash
# (On a machine where a wallet is accessible in Lotus)
> ./delta-dm wallet import --hex $(lotus wallet export f1mmb3lx7lnzkwsvhridvpugnuzo4mq2xjmawvnfi)
```

### 2a. Associate wallet with dataset
**By UI**
Find the wallet in the DDM UI, and click the **Associate With Dataset** button below it.

Select the dataset you added previously, and click **Apply**

<img src="../assets/ddm-associate-wallet.png" width=400/>

**By CLI**
```bash
./delta-dm wallet associate --address f1mmb3lx7lnzkwsvhridvpugnuzo4mq2xjmawvnfi --dataset radiant-earth-ml 
```

### 3. Add Content to Dataset
There are a number of ways to associate content with a dataset.

Note: Piece CIDs / CommP's must be globally unique in DDM - thus, you don't have to worry about collisions when importing content from other CAR generation tools - the duplicates will simply not be added. This allows you to progressively import content from those tools as they are generated, without needing to "diff" the CID list.

#### Importing from other CAR generation tooling
**Singularity Content**
Follow the instructions in the [Singularity Import Guide](https://github.com/application-research/delta-dm/blob/main/docs/singularity-import.md))

**Ptolemy Content**
Follow the instructions in [Ptolemy Import Guide](https://github.com/application-research/delta-dm/blob/main/docs/ptolemy-import.md)

#### Importing from CSV/JSON file
**By UI**
Click on the `Datasets` button on the top left corner of the DDM UI. Click the `Attach Content` button below the dataset you created previously. 

<img src="../assets/ddm-attach-content-button.png" width=300/>

After that, you can either click Attach Content or drag and drop the file into the UI.

JSON Format: Consult the [DDM Format](https://github.com/application-research/delta-dm/blob/main/docs/api.md#delta-dm-format) spec for a description of the JSON schema you need to follow. 

**By CLI**
```bash
# json file
./delta-dm content import --dataset radiant-earth-ml --json ./content.json

# OR csv file
./delta-dm content import --dataset radiant-earth-ml --csv ./content.csv
```

### 4. Add Provider(s)
**By UI**
Click on the `+ Add Provider` button on the top left corner of the DDM UI. Enter the SP's address (f0######), and an optional friendly name.

<img src="../assets/ddm-add-provider.png" width=400/>

**By CLI**
```bash
./delta-dm provider add --address f011111 --name "My Provider"
```

### 4a. Associate Provider with datasett

**By UI**
From the **Providers** pane, click the **Manage [SP ID]** button. Under the **Allowed Datasets** section, click **Add**, select the dataset you created previously, and click **Apply**.

**By CLI**
> optionally, enable self-service
```bash
./delta-dm provider modify --id f011111 --allowed-datasets radiant-earth-ml --allow-self-service on
```

### 5. Create Replications!

**By UI**
Click the **Add Replication** button in the top left-hand corner of the DDM UI. Select the provider, and (optionally) select a dataset to replicate. Choose the number of deals, days to delay start epoch, and then click **Add**.

<img src="../assets/ddm-add-replication.png" width=400/>

Wait a few seconds - the deal(s) will be made with the provider and show up in the DDM Replications tab.

**By CLI**
```bash
./delta-dm replication create --provider f011111 --num 1 --dataset radiant-earth-ml --delay-start 7
```

**By SP Pulling deal (Self-Service)**
First, enable self-service for the provider by visiting the **Providers** tab, and clicking **Edit**, and checking the **Allow Self Service** checkbox. Securely share the **Provider Key** with the SP, as they'll use this to request deals from DDM.

<img src="../assets/ddm-allow-ss.png" width=400/>

In order to make a deal request, your ddm API (i.e, `http://localhost:1314/api/v2/self-service`) must be reachable by them. To set easily set this up, we recommend configuring a reverse proxy like [Caddy](https://caddyserver.com/) or [Nginx](https://nginx.org/en/).

Check out [Delta Importer](https://github.com/application-research/delta-importer), which can be configured in either **Pull Dataset** or **Pull CID** mode to automatically pull deals from DDM. 

For an SP to manually make a request for a deal, share the following **cURL** command with them, as an example:

```bash
# Pull a deal for a specific dataset
curl --request GET \
  --url 'http://your-delta-dm-address-here/api/v1/self-service/by-dataset/dataset-name?start_epoch_delay=3' \
  --header 'X-DELTA-AUTH: xxx-xxx-xxx-xxx'

# Pull a deal for a specific CID
curl --request GET \
  --url 'http://your-delta-dm-address-here/api/v1/self-service/by-cid/cid?start_epoch_delay=3' \
  --header 'X-DELTA-AUTH: xxx-xxx-xxx-xxx'
```

For more information on the API, see the [DDM Self-Service documentation](https://github.com/application-research/delta-dm/blob/main/docs/self-service.md)

**Comment by alvin-reyes** [comment]
Any guides should either be in the wiki or docs folder of the project. This issue tab is only for bugs, feature request, and any custom request from someone external for the core team. Let’s move this to the proper docs please.

**Comment by jimmylee** [comment]
I'm just doing this as an example for how easy it is to represent a markdown file as documentation. So you could simply create a https://github.com/application-research/documentation repository, or anything of the sort.

**Comment by jimmylee** [comment]
Example of a reference that this file has moved: https://github.com/application-research/delta-docs/issues/1
